services:
  - type: web
    name: ai-interview
    runtime: node
    plan: standard
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: ARCJET_ENV
        value: production
      - key: NEXT_PUBLIC_STREAM_API_KEY
        sync: false
      - key: STREAM_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false